### PR TITLE
Use custom font

### PR DESCRIPTION
**Pull request by JolandaVerhoef**
This PR consists of two parts:
1. Replace all occurrences of `fontFamily = FontFamily("Roboto")` with `fontFamily = appFontFamily`, where `appFontFamily` links to the `CircularStd` font.
2. Add a default typography to the Material Theme that overrides all font families with `CircularStd`

### CODE REVIEW

**Comment by zsoltk** [comment]
Thank you! One issue I see is that on the new screenshot, all texts moved upwards somewhat. It's especially visible on menu item texts and search bar text which lost its vertical centering. I wonder if that can be fixed with any font setting without manually changing positionings all around the app?

**Comment by JolandaVerhoef** [comment]
I've been looking at it, but can't figure it out. Maybe you can help. What would cause the text to be aligned correctly in the first place? For example, if we look at the `RoundedSearchBar` it contains a `Row` which contains the image, a Spacer, and a Text. Why would the Text there be vertically aligned within the room that the image is taking? Is that a property of the `Row`?

**Comment by JolandaVerhoef** [comment]
I've done some more investigation, here are my findings:

On master, we can look at the Preview with and without the material theme applied. We see that the material version correctly aligns the text in the center, which seems to be coincidence since the non-material themed version has a smaller font which isn't aligned in the center.
image

When we just change the font size of the text in the search bar, we see the same effect:
```
Text("Search Pokemon, Move, Ability, etc",
                    style = MaterialTheme.typography().body1.copy(fontSize = 8.sp))
```
image

When we use a custom font, the height of this font will naturally be a bit different from the Roboto font. Since changing the height leads to issues with alignment when we didn't explicitly align the Text composable, we see that the custom font is not aligned well.

I would propose to fix this by explicitly aligning the text in the center of its parent. I'll give that a try next!

**Comment by JolandaVerhoef** [comment]
Search bar and menu item have been fixed to correctly align. For the Search bar, I used LineItem from Compose toolkit as a reference. 

New screenshot:

**Comment by zsoltk** [comment]
Amazing job there @JolandaVerhoef, thanks for all your time and effort!

**Pull request merged**
